export interface Placard {
  id: number;
  title: string;
  message: string;
  accent?: "rose" | "gold" | "lavender" | "peach";
}

export const placards: Placard[] = [
  { id: 1, title: "A Thing I Never Told You", message: "Every time you laughed, I quietly memorized the sound — afraid one day it would only exist inside me.", accent: "rose" },
  { id: 2, title: "What I Miss Most", message: "The way your eyes softened mid-sentence, like you forgot you were guarded around the rest of the world.", accent: "gold" },
  { id: 3, title: "A Moment I Ruined", message: "I chose pride when I should have chosen you. I think about that hour more than I think about anything I have ever done well.", accent: "rose" },
  { id: 4, title: "You Deserved Better", message: "Not someone louder. Not someone newer. Just someone braver — and I want to learn how to be him.", accent: "lavender" },
  { id: 5, title: "Why Your Smile Still Lives In My Head", message: "Because it was the first thing that ever made silence feel like company.", accent: "peach" },
  { id: 6, title: "The Softest Memory", message: "Your hand finding mine under the table — without looking, without thinking. Like coming home in a single second.", accent: "rose" },
  { id: 7, title: "If I Could Redo One Day", message: "I would choose the one I wasted being right. I would lose every argument again just to keep you smiling that morning.", accent: "gold" },
  { id: 8, title: "A Tiny Piece Of My Heart", message: "There is a corner of it that only knows your name. It refuses to learn anyone else's.", accent: "rose" },
  { id: 9, title: "The Version Of Me You Deserved", message: "Patient. Present. Soft when it mattered. I am still becoming him — and you were the reason I started.", accent: "lavender" },
  { id: 10, title: "Three Words I Should Have Said First", message: "Not 'I love you.' Those came easily. The harder three were: 'I am sorry.'", accent: "gold" },
  { id: 11, title: "Your Favorite Song", message: "I cannot listen to it anymore without seeing you in the passenger seat, eyes closed, mouthing the chorus like a prayer.", accent: "peach" },
  { id: 12, title: "A Confession", message: "I read our old messages when the nights get long. I do not look for excuses. I look for the moment I stopped being kind.", accent: "rose" },
  { id: 13, title: "The Way You Said My Name", message: "Like it belonged to someone worth loving. I have not heard it sound that way since.", accent: "gold" },
  { id: 14, title: "A Promise", message: "If you ever let me back in, I will protect that door like it is the only one I have ever been given.", accent: "rose" },
  { id: 15, title: "Something Small I Noticed", message: "How you always tucked your hair behind your ear before saying something honest. I miss the warning.", accent: "lavender" },
  { id: 16, title: "On The Bad Nights", message: "I do not picture us fighting. I picture you on the couch, asleep mid-sentence, and me — finally quiet enough to listen.", accent: "rose" },
  { id: 17, title: "Why I Disappeared", message: "Not because I stopped caring. Because I was afraid you would see me clearly and decide I was not enough.", accent: "peach" },
  { id: 18, title: "A Letter I Never Sent", message: "It started with 'I am sorry' and ended with 'please.' Everything in between was just a long way of asking you to stay.", accent: "gold" },
  { id: 19, title: "The Look I Miss", message: "The one right before you kissed me — half a question, half certainty. No one has ever looked at me like that since.", accent: "rose" },
  { id: 20, title: "What I Learned Too Late", message: "Love is not loud. It is the steady hand. It is the unglamorous apology. It is staying when leaving would be easier.", accent: "lavender" },
  { id: 21, title: "A Quiet Wish", message: "That somewhere, in some version of this story, I got it right the first time.", accent: "gold" },
  { id: 22, title: "Your Laugh", message: "Was the only thing that ever made me believe joy was a real, measurable substance.", accent: "peach" },
  { id: 23, title: "A Memory In A Box", message: "The receipt from the first coffee. I kept it. It is folded in a book you bought me. I never told you.", accent: "rose" },
  { id: 24, title: "The Truth", message: "I was not too cool to care. I was too scared to show how much I did.", accent: "lavender" },
  { id: 25, title: "If You Are Reading This", message: "Take your time. There is nowhere in this little universe that I am not waiting patiently.", accent: "gold" },
  { id: 26, title: "Your Kindness", message: "Was never weakness. It was the strongest thing in any room you walked into. Including mine.", accent: "rose" },
  { id: 27, title: "A Soft Apology", message: "For the silences I chose. For the words I rationed. For making you wonder if you were too much, when you were exactly enough.", accent: "peach" },
  { id: 28, title: "The First Time", message: "I knew was a Tuesday. Nothing special happened. You yawned. I thought: 'Oh. There it is. The rest of my life.'", accent: "gold" },
  { id: 29, title: "What Your Presence Did", message: "It turned ordinary rooms into places I wanted to stay in. It made afternoons feel like something worth remembering.", accent: "rose" },
  { id: 30, title: "A Hidden Note", message: "If hearts could be repaired by intention alone, yours would already be made of gold again. Mine is trying.", accent: "lavender" },
  { id: 31, title: "Why I Am Doing This", message: "Not to win you back. To tell you the truth — because you always deserved it, and I gave you everything except.", accent: "gold" },
  { id: 32, title: "The Way You Loved Me", message: "Without performance. Without keeping score. Just steady, patient, generous love. I see it clearly now.", accent: "rose" },
  { id: 33, title: "An Old Photograph", message: "You are looking away from the camera. I am looking at you. That is the whole story, and I missed it for too long.", accent: "peach" },
  { id: 34, title: "Things I Notice Now", message: "How rare you were. How quiet your softness was. How loud my mistakes feel in comparison.", accent: "lavender" },
  { id: 35, title: "A Confession In The Dark", message: "I sleep on the left side now. I am leaving the right side empty out of habit, or hope, or both.", accent: "rose" },
  { id: 36, title: "The Truest Thing", message: "You were never hard to love. I was just hard at the wrong moments.", accent: "gold" },
  { id: 37, title: "What I Want To Build", message: "Not the relationship we had. A better one. Slower. Softer. With everything I was too young to give the first time.", accent: "rose" },
  { id: 38, title: "Your Heart", message: "Was the gentlest place I have ever been allowed to enter. I will not forget the privilege of that, ever.", accent: "lavender" },
  { id: 39, title: "An Easter Egg", message: "You found one of the rare ones. Consider this a small kiss on the forehead from across the universe.", accent: "gold" },
  { id: 40, title: "If Time Bent", message: "I would not change the meeting. I would change the man who met you. He needed more years to become worthy of yours.", accent: "rose" },
  { id: 41, title: "The Last Argument", message: "Was not about what we said it was about. It was about every unspoken fear I never let you hold for me.", accent: "peach" },
  { id: 42, title: "A Small Vow", message: "To never again confuse distance for safety. To never again treat your patience as something I had earned forever.", accent: "gold" },
  { id: 43, title: "The Memory I Replay", message: "You, in my hoodie, on the kitchen floor, laughing at something I cannot remember. The light was gold. You were gold.", accent: "rose" },
  { id: 44, title: "A Whisper", message: "I miss you in a way that does not feel like longing. It feels like reverence.", accent: "lavender" },
  { id: 45, title: "What Healing Looks Like", message: "Is not erasing you. It is learning to carry the love properly — without dropping it on someone who never deserved to catch it.", accent: "gold" },
  { id: 46, title: "Your Name", message: "Still has a different weight than every other word in my vocabulary. I think it always will.", accent: "rose" },
  { id: 47, title: "The Quiet Compliment", message: "You made love feel gentle. Most people in this lifetime never get to learn what that means. You taught me.", accent: "peach" },
  { id: 48, title: "If You Are Still Here", message: "Thank you. For reading. For staying long enough to let me say it slowly, the way you always deserved.", accent: "gold" },
  { id: 49, title: "A Real Promise", message: "If there is a second chance — even a small one — I will not be loud about it. I will just show up. Every day. Quietly. Surely.", accent: "rose" },
  { id: 50, title: "The Universe Itself", message: "Broke apart a little, just to make something delicate enough to hand to you. I hope you can feel that.", accent: "lavender" },
  { id: 51, title: "Your Softness", message: "Even silence felt softer around you. That is a kind of magic most people never produce in a lifetime.", accent: "rose" },
  { id: 52, title: "A Forgotten Detail", message: "Your favorite mug had a tiny chip on the handle. You held it like it was perfect anyway. You held me the same way.", accent: "gold" },
  { id: 53, title: "The Honest Version", message: "I was not bored. I was not done. I was overwhelmed by how much I had to lose, and I lost it trying to protect myself from losing it.", accent: "peach" },
  { id: 54, title: "Why You Are Irreplaceable", message: "Because no second version of a person ever arrives. You were the only edition. There will never be another.", accent: "rose" },
  { id: 55, title: "A Tiny Universe", message: "I built this entire little world from things I never said. Every glow, every star — a sentence I owed you.", accent: "gold" },
  { id: 56, title: "The Last Placard", message: "If you have opened this one, you have read my whole heart. There is nothing hidden anymore. Just this: I am sorry, and I am here.", accent: "rose" },
];

export const reasons = [
  "You Made Love Feel Gentle.",
  "Your Presence Turned Ordinary Days Into Memories.",
  "Even Silence Felt Softer Around You.",
  "You Deserved The Kindest Version Of Me.",
  "You Were Never Hard To Love.",
  "Your Heart Was The Quietest, Bravest Room I Have Ever Been In.",
  "You Made Mornings Worth Waking Up For.",
  "You Taught Me That Tenderness Is A Skill, Not A Weakness.",
];

export const letters = [
  { id: "l1", title: "Letter I", body: "I have rewritten this a hundred times. None of the versions sound like enough. So here is the smallest, truest one: I am sorry. Not for parts. For all of it." },
  { id: "l2", title: "Letter II", body: "If forgiveness is too much to ask, then please accept this instead — proof that I understood, eventually, exactly what I had." },
  { id: "l3", title: "Letter III", body: "I am not asking you to come back. I am asking you to know, with certainty, that you were loved well at least once — even if I was bad at showing it." },
  { id: "l4", title: "Letter IV", body: "Whatever you decide, decide it slowly. You are allowed to take as long as you need. I will be exactly here, holding the door open without rushing you through it." },
  { id: "l5", title: "Letter V", body: "Thank you. For the patience you already spent. For the love you already gave. None of it was wasted on me. I am keeping it, gently, for the rest of my life." },
];

export const constellationMessages = [
  "You are the softest thing my life has ever held.",
  "I would choose you again. And again. And again.",
  "There is no version of this story where I forget your kindness.",
  "Your laugh lives rent-free in the best part of my memory.",
  "I am proud of you, even from this distance.",
  "I hope someone tells you today how rare you are.",
  "Your name is still the warmest word I know.",
  "I am sorry. Truly. Patiently. Without conditions.",
  "You were the gold standard. You still are.",
  "Whatever happens — I am grateful you existed in my life at all.",
  "I promise to be softer the second time around.",
  "You taught me how to love quietly.",
];
